### ISSUE TITLE
tactics not implemented in techniques

### ISSUE THREAD

**Issue by tlhendri** [swimlane/pyattck#1]
This doesn't seem to work:
```
for technique in attack.techniques:
    print(technique)

    # accessing tactics that this technique belongs to
    for tactic in technique.tactics:
        print(tactic)
```
From usage examples https://pypi.org/project/pyattck/

Tactics also don't seem to be fully returned when using the tactic:
```
# accessing tactics
for tactic in attack.tactics:
    #print(tactic.id, [technique.id for technique in tactic.techniques])
    if 'T1098' in [technique.id for technique in tactic.techniques]:
        print(tactic.id)
```
```    
for technique in attack.techniques:
    #print(technique.id,[tactic.id for tactic in technique.tactics]) - doesnt work
    #print(technique.id,[tactic.id for tactic in technique.tactic]) - works
    if technique.id == 'T1098':
        print([tactic.id for tactic in technique.tactic])
    
#https://attack.mitre.org/techniques/T1078/
#Tactics = Defense Evasion - confirmed, Persistence - confirmed, Privilege Escalation - confirmed, Initial Access - confirmed
#4 listed at site, only two returned. when using the tactic method of technique only one returned.
```

**Comment by skyWalker1997** [comment]
Same question, I read the technique.py in pyattck package and I found out something strange.

<img width="439" alt="image" src="https://user-images.githubusercontent.com/25174981/61838868-e07f4580-aebd-11e9-8db3-d2ffdb76ffb8.png">

`temp_list = phase['phase_name']` in def tactic(self, obj),line71  caused every technique reflected only one tactic rather than a list of tactic, which is incorrect.

**Comment by skyWalker1997** [comment]
With the question I mentioned above, the function '@property def tactic(self)'  also has a bug.
<img width="610" alt="image" src="https://user-images.githubusercontent.com/25174981/61840427-bc266780-aec3-11e9-8a30-c424884a15ba.png">
Attention line 50 to line 52
cause self._tactic return a list.Then ,you can't  compare a 'str(list).lower()' with a 'str().lower()'
It won't cause fault when a technique only belong to one tactic.But when a technique belong to several  
tactics ,it will cause problem.
So to fix it ,you should traversal each tactic that self got, and then compare the each  str(tactic).lower with str(item['x_mitre_shortname']).lower()

Here is my code:


` def tactic(self):
        '''Returns all tactics as a list that this technique is found in'''
        from .tactic import AttckTactic
        tactic_list = []
        for item in self.attck_obj['objects']:
            if 'x-mitre-tactic' in item['type']:
                for tactic_temp in self._tactic:
                    if str(tactic_temp).lower() ==  str(item['x_mitre_shortname']).lower():
                        tactic_list.append(AttckTactic(**item))
        return tactic_list`

**Comment by joshswimlane** [comment]
@tlhendri & @skyWalker1997 Can you please create an issue for each of these and I will make the appropriate changes.  Reading through this it looks like there are 3 or 4 issues here it would be easier to resolve each in their own individual issues.

I will be begin looking at these.  Thanks for bringing them up!

**Comment by skyWalker1997** [comment]
> them

No problem

**Comment by joshswimlane** [comment]
This should be fixed - pushing to pypi soon
