### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by juancar1979** [swimlane/pyattck#105]
**Describe the bug**
The problem is with the Industroyer malware. It seems that the data_source used to get the info from it is not well formed. When doing a split it gives more than two values (the expected)
attack-datasources/network_traffic.yml at main - mitre-attack/attack-datasources

It happens since the last pyattack update.

![bug1](https://user-images.githubusercontent.com/5212618/165534692-b5149723-d2d1-4af1-a77b-9df77149d2fe.jpg)
![bug0_1](https://user-images.githubusercontent.com/5212618/165534741-96f41a08-637e-4837-9304-abb8a9548c61.png)
![bug0_2](https://user-images.githubusercontent.com/5212618/165534758-5cf2d6d3-a312-4c0c-8442-27aef80d4b90.png)

**To Reproduce**

"for technique in malware.techniques:" with malware "Industroyer"

**Expected behavior**
NA

**Screenshots**
Added in explanation

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]. Windows 10
 - Browser [e.g. chrome, safari] NA
 - Version [e.g. 22] NA

**Smartphone (please complete the following information):** NA

**Additional context**

**Comment by MSAdministrator** [comment]
@juancar1979 I am unable to reproduce this - can you provide the code you used to reproduce this ?

I tried 

```
from pyattck import Attck

attack = Attck()

for malware in attack.enterprise.malwares:
    if malware.name == 'Industroyer':
        for tech in malware.techniques:
            print(tech.data_sources)
  
```

**Comment by juancar1979** [comment]
attack = Attck()
malware_name = "Industroyer"
for malware in attack.ics.malwares:
    print(malware.name)
    if malware.name == malware_name:
        techMatrixICS = {}
        for technique in malware.techniques:
            tacticas = {}
            mitigations = {}

**Comment by juancar1979** [comment]
#

> @juancar1979 I am unable to reproduce this - can you provide the code you used to reproduce this ?
> 
> I tried
> 
> ```
> from pyattck import Attck
> 
> attack = Attck()
> 
> for malware in attack.enterprise.malwares:
>     if malware.name == 'Industroyer':
>         for tech in malware.techniques:
>             print(tech.data_sources)
>   
> ```
attack = Attck()
malware_name = "Industroyer"
for malware in attack.ics.malwares:
print(malware.name)
if malware.name == malware_name:
techMatrixICS = {}
for technique in malware.techniques:
tacticas = {}
mitigations = {}

**Comment by caesarshift** [comment]
This code reproduces the stacktrace listed in this ticket:

```
from pyattck import Attck
attck = Attck()
print(attck.ics.techniques)
```

The code on line 94 of `pyattck/ics/attckobject.py` assumes that the data item only contains 1 colon:

```
data_source, data_component = item.split(':')
```

However, I'm seeing this present in an "item" variable:

`Network Traffic: Network Traffic Flow  [https://github.com/mitre-attack/attack-datasources/blob/main/contribution-ics/network_traffic.yml Network Traffic: Network Connection Creation`

So either the data for this item needs to be correct, or the line of code needs to be updated to only split on the first colon:

```
data_source, data_component = item.split(':', 1)
```
