### ISSUE TITLE
Pyattck 5.4 not working with current data model

### ISSUE THREAD

**Issue by phantinuss** [swimlane/pyattck#108]
Current pyattck 5.4 does not work in combination with the downloaded data model.
```
Traceback (most recent call last):
[...]
  File "/home/[...]/venv/lib/python3.10/site-packages/pyattck/enterprise/enterprise.py", line 294, in actors
    self.__actors.append(AttckActor(attck_obj=self.__attck, **group))
  File "/home/[...]/venv/lib/python3.10/site-packages/pyattck/enterprise/actor.py", line 106, in __init__
    self.external_dataset = self.__get_actors_dataset()
  File "/home/[...]/venv/lib/python3.10/site-packages/pyattck/enterprise/actor.py", line 120, in __get_actors_dataset
    for actor in val.get('actors'):
AttributeError: 'str' object has no attribute 'get'
```

The error occurs during calling the `__get_actors_dataset` function of `actor.py`

**Expected behavior**
Data is returned so that the library code can handle it.

**Screenshots**
![image](https://user-images.githubusercontent.com/79651203/171364834-946cb532-0d12-4df5-8b86-fff20a145454.png)

I think you should be easily able to reproduce this issue. If not, I am happy giving further details.

**Comment by phantinuss** [comment]
Update: In our code we have a hotfix now and overwrite the downloaded data with the one available on github:
```
Attck(generated_attck_json="https://github.com/swimlane/pyattck/blob/master/generated_attck_data.json?raw=True")
```

**Comment by MSAdministrator** [comment]
@phantinuss Sorry about that - I caused this and have since resolved it. Please let me know if this is *NOT* resolved
