### ISSUE TITLE
Techniques Return Empty Tactics Array

### ISSUE THREAD

**Issue by Still34** [swimlane/pyattck#116]
**Describe the bug**
The `Technique` object should return its associated `Tactics`, but at the moment it returns an empty array.

**To Reproduce**
1. Select any ATT&CK Enterprise technique
2. View the `Tactics` member associated with the technique
3. Empty results

**Expected behavior**
The technique should return its associated tactics.

**Screenshots**
![image](https://user-images.githubusercontent.com/5843208/174970072-376679de-d875-4d72-aa93-cc686235af59.png)

**Comment by liavst2** [comment]
Having the same issue, in version 6.1.2.
