### ISSUE TITLE
simple example sub technique exception

### ISSUE THREAD

**Issue by robomotic** [swimlane/pyattck#117]
Just running the first example:

<img width="609" alt="image" src="https://user-images.githubusercontent.com/315964/175405203-949dd58d-eee4-449f-bbae-f0250d42a463.png">

**Comment by MSAdministrator** [comment]
@robomotic This has changed but the test.py did not get updated properly.

It should be 

```python
from pyattck import Attck

attack = Attck()

for technique in attack.enterprise.techniques:
    print(technique.id)
    print(technique.name)
    for subtechnique in technique.techniques:
        print(subtechnique.id)
        print(subtechnique.name)
```
