### ISSUE TITLE
groups linkage to techniques

### ISSUE THREAD

**Issue by robomotic** [swimlane/pyattck#118]
**Is your feature request related to a problem? Please describe.**
I want an interface to pull the relationships between Groups and Techniques.

**Describe the solution you'd like**
For example on the MITRE website: https://attack.mitre.org/groups/G0016/
For each group there is a list of the techniques used.
I am not sure where those relationships are stored in STIX but would be nice to have an object or a utility that given a technique ID or an actor ID returns the corresponding linked objects.

**Describe alternatives you've considered**
Right now I webscrape the webpage with pandas.

**Additional context**

**Comment by priamai** [comment]
Actually my bad, looking at the data model this is perfect.

```
from pyattck import Attck

attack = Attck()

for actor in attack.enterprise.actors:
  print(f'Actor Name {actor.name} Total techniques {len(actor.techniques)}')
```

Closing now.
