### ISSUE TITLE
Lack of Procedures description

### ISSUE THREAD

**Issue by ablescia** [swimlane/pyattck#131]
**Is your feature request related to a problem? Please describe.**
I can't find the procedure description for each techniques belongs to a group.

**Describe the solution you'd like**
I need to retrieve the procedure description for each techniques describe in the Technique used table.

For instance:
- group: apt18
- technique: 1547.001
- procedure: APT18 establishes persistence via the HKCU\Software\Microsoft\Windows\CurrentVersion\Run key.

I need the text inside the procedure field.

**Comment by MSAdministrator** [comment]
@ablescia I have updated the Enterprise framework to suypport the `relationship` data type. In the next release you will be able to run something like this to get each relationship usage.

```python
for relationship in attack.enterprise.relationships:
    print(relationship.id)
    print(relationship.description)
```
