### ISSUE TITLE
Error when trying to iterate through techniques

### ISSUE THREAD

**Issue by TiiTcHY** [swimlane/pyattck#136]
**Describe the bug**
when using the example for iterating through the techniques i get the a keyword argument "socks_support"

for technique in attack.enterprise.techniques:
    print(technique.id)

TypeError: __attrs_init__() got an unexpected keyword argument 'socks_support'

**To Reproduce**
- Create a python script with the following code: 
from pyattck import Attck
attack = Attck()
for technique in attack.enterprise.techniques:
    print(technique.id)

**Expected behavior**
i would expect a print out of the current MITRE Techniques

currently using pyattck 7.1.1

**Comment by MSAdministrator** [comment]
This should be resolved now. Please reopen if not.
