### ISSUE TITLE
Performance refactor

### ISSUE THREAD

**Issue by ehooo** [swimlane/pyattck#15]
Hello @joshswimlane 
I was working on a [new refactor](https://github.com/ehooo/pyattck/tree/feature/memory_improvement) for improve the performance of pyattck.
I wanted to improve the memory usage, unfortunately it was not possible, but the time to parsing the file was huge improvement.

If you want i could create the pull request, it could be a new mayor version on the project.
Also i think it could useful create a test for the project.

Please give me feedback about what you think.

Here you are the results and test files used [pyattck_test.zip](https://github.com/swimlane/pyattck/files/3774920/pyattck_test.zip):

### New code:
```
Memory:
	Max: 71.02Mb
	Min: 19.47Mb
	Median(6): 47.31Mb
Time mem: 0:00:00.353103
```
### Old code:
```
Memory:
	Max: 78.98Mb
	Min: 17.62Mb
	Median(721): 70.28Mb
Time mem: 0:01:12.166692
```
### New code:
```
Memory:
	Max: 43.66Mb
	Min: 22.96Mb
	Median(5): 34.12Mb
Time mem: 0:00:00.223263
```
### Old code:
```
Memory:
	Max: 42.43Mb
	Min: 21.35Mb
	Median(299): 42.16Mb
Time mem: 0:00:29.845125
```

### New code:
```
Memory:
	Max: 41.73Mb
	Min: 22.92Mb
	Median(5): 32.11Mb
Time mem: 0:00:00.221237
```
### Old code:
```
Memory:
	Max: 45.91Mb
	Min: 21.18Mb
	Median(250): 40.53Mb
Time mem: 0:00:24.916879
```

### New code:
```
Memory:
	Max: 41.21Mb
	Min: 21.81Mb
	Median(5): 31.23Mb
Time mem: 0:00:00.232362
```
### Old code:
```
Memory:
	Max: 41.25Mb
	Min: 21.00Mb
	Median(321): 41.04Mb
Time mem: 0:00:32.049158
```

**Comment by joshswimlane** [comment]
Awesome! I’ll have to look at this next week - I’m on vacation currently - but thanks!

**Comment by ehooo** [comment]
Have you time to make a look? let me know to create the pull request if you cant.

**Comment by joshswimlane** [comment]
Hey @ehooo I have not yet, but I will do so this week.  I would go ahead and make a pull request, which will be easier to review anyways.  Thanks!

**Comment by ehooo** [comment]
@joshswimlane did you have time for see it?
I think is better see directly in the code better than the diffing.

**Comment by ehooo** [comment]
@joshswimlane now the PR is failing cause `KeyError: 'GH_TOKEN'` do you know how could i fix it?
I just update the PR branch

**Comment by joshswimlane** [comment]
This has been resolved.  If the issue persists please open a new issue.
