### ISSUE TITLE
Pyattack not collecting Newly updated data

### ISSUE THREAD

**Issue by le0li9ht** [swimlane/pyattck#21]
For example when i'm trying to get the APT16 and APT17 cells i'm getting empty data.
![Screenshot from 2019-12-23 19-04-40](https://user-images.githubusercontent.com/34128579/71360855-29474180-25b7-11ea-8e6b-985430aeb010.png)

**Comment by daniberh** [comment]
I think this is because APT16 and APT17 only have PRE-ATT&CK techniques and not enterprise techniques.

https://attack.mitre.org/groups/G0023/
https://attack.mitre.org/groups/G0025/

**Comment by joshswimlane** [comment]
You are correct @daniberh - closing this out.
