### ISSUE TITLE
Did you really update the object's structure in bugfix version release?

### ISSUE THREAD

**Issue by Neo23x0** [swimlane/pyattck#40]
Using 2.0.4
```
Using cached https://files.pythonhosted.org/packages/88/36/e2ac6dcc310a8d5654e0c06c8f935fc60cc700cbadcac05a0facb54e0bb1/pyattck-2.0.4-py3-none-any.whl
```
I have no errors. 

Using 2.0.5
```
Downloading https://files.pythonhosted.org/packages/f5/50/80cac42fc2da54d3a924d5886c8c94034fa53121af36879d42bc3cb7ca38/pyattck-2.0.5-py3-none-any.whl (934kB)
```
i suddenly get:
```
AttributeError: 'AttckActor' object has no attribute 'aliases'
```

Did you really change the object's structure from 2.0.4 to 2.0.5? 
Could you please introduce breaking changes in major (X.0.0) or at least feature (0.X.0) releases only?

**Comment by joshswimlane** [comment]
@Neo23x0 this update modified the property name of “aliases” to “alias”. MITRE has both (now) Json keys of “x_mitre_aliases” and “alias” so combined them into one property.

Going forward I’ll make this adjustment if properties are modified, changed, or removed.
