### ISSUE TITLE
Traceback when calling actors from attack.techniques

### ISSUE THREAD

**Issue by nbyt3** [swimlane/pyattck#42]
Pyattck v2.0.5

```
for tactic in attack.tactics:
    for technique in tactic.techniques:
          for actor in technique.actors:
              print(actor)
```

results in: 
'Traceback (most recent call last):\n  File "c:\\Users\\.vscode\\extensions\\ms-python.python-2020.7.96456\\pythonFiles\\lib\\python\\debugpy\\_vendored\\pydevd\\_pydevd_bundle\\pydevd_resolver.py", line 193, in _get_py_dictionary\n    attr = getattr(var, name)\n  File "C:\\Users\\Documents\\Projects\\feeds\\venv\\lib\\site-packages\\pyattck\\enterprise\\technique.py", line 190, in actors\n    for item in self.__attck_obj[\'objects\']:\nTypeError: \'NoneType\' object is not subscriptable\n'

**Comment by joshswimlane** [comment]
@nbyt3 Thanks for posting this.  This is actually not a bug but I see why you would think it is.  Currently pyattck only supports defined relationships by Mitre and does not assume further relationships.  These relationships are typically 2 layers deep. 

But, What I'm going to do is make this as a feature request and will work on this as time permits. Thanks again!

**Comment by Mars-Lourd** [comment]
Hello,
I wanted to know if you had corrected this problem?
I have the same problem and I would like to know if it's now possible to go further than 2 layers?
Thanks a lot !

**Comment by MSAdministrator** [comment]
Hey @Mars-Lourd I have an active pull request #49 that I believe will resolve this issue.  I'll try and get it published today.
