### ISSUE TITLE
Pyattck json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by TiiTcHY** [swimlane/pyattck#54]
When ever I try to run anything after re-installing 3.0.0 of pyattck i'm getting the following error:

for technique in attack.enterprise.techniques:

error - json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by MSAdministrator** [comment]
Yeah @TiiTcHY I just pushed a new updated version of the generated_attck_data.json - please remove the `pyattck` folder in your ~/ user directory.  Then re-run and it should be resolved.  My merge got messed up for some reason.

**Comment by MSAdministrator** [comment]
@TiiTcHY actually just found a bug - basically the issue is that I move to git-lfs so the download of external data is having issues - I know a fix and will push that soon.

**Comment by MSAdministrator** [comment]
@TiiTcHY Please remove the current version and install pyattck==3.0.1 (make sure to remove the pyattck folder containing your config in your user directory.
