### ISSUE TITLE
2.1.0 and 2.1.3 return ValueError: No JSON object could be decoded.

### ISSUE THREAD

**Issue by jmeachum** [swimlane/pyattck#56]
>>> from pyattck import Attck
>>> attck = Attck().update(enterprise=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\dev\swimlane_4_1_env\lib\site-packages\pyattck\attck.py", line 365, in update
    self.__load_data(force=True)
  File "C:\dev\swimlane_4_1_env\lib\site-packages\pyattck\attck.py", line 379, in __load_data
    Attck.__ENTERPRISE_GENERATED_DATA_JSON = self.__datasets.generated_attck_data(force=force)
  File "C:\dev\swimlane_4_1_env\lib\site-packages\pyattck\datasets.py", line 77, in generated_attck_data
    datasets = self.__get_datasets()
  File "C:\dev\swimlane_4_1_env\lib\site-packages\pyattck\datasets.py", line 101, in __get_datasets
    return requests.get(self.__DATASETS_URL).json()
  File "C:\dev\swimlane_4_1_env\lib\site-packages\requests\models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "C:\dev\Python2714\Lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "C:\dev\Python2714\Lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\dev\Python2714\Lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by MSAdministrator** [comment]
Please upgrade to the latest if possible:

pip install pyattck—upgrade 

if not then I will attempt to resolve this but upgrading is the best option.

**Comment by jmeachum** [comment]
Yes I confirmed it gets past that but the breaking changes in 3.0 will require refactoring quite a bit of code to get back to working state. It would be great to have had tests for this against 2.x code base, or some form of backwards compatibility.

**Comment by MSAdministrator** [comment]
The reason was that the external data was getting too large so I had to switch to git-lfs which means a different url format/path. It was unexpected but needed to happen. I’ll push some new files but I’m not sure how much longer they will be available. I’ll try and get this done tonight or tomorrow morning. Apologies for any interruptions.

**Comment by jmeachum** [comment]
Thanks for the explanation and appreciate the response. We happen to have built this into a production SL app so I'll need to work on getting cutover to the latest version.

**Comment by MSAdministrator** [comment]
No problem and sorry for any troubles.  A quick fix to get up and running is doing something like this to set the value to the new URL (this is for the generated data):

```
from pyattck import Attck

attck = Attck()

attck.__ENTERPRISE_GENERATED_DATA_JSON = 'https://github.com/swimlane/pyattck/blob/master/generated_attck_data.json?raw=True'
```

**Comment by MSAdministrator** [comment]
@jmeachum are you using this as part of the Swimlane plugin or stand-alone (e.g. python task)?  If you need help either way I'll try and do my best to facilitate/assist.

**Comment by jmeachum** [comment]
@MSAdministrator - A couple of stand-alone tasks. We are using it for tagging alerts against the framework and use it for contextual data. I should be able to get us current with 3.0.1 but concerned when this will break our prod application that uses it.

**Comment by MSAdministrator** [comment]
Is there functionality that has changed ? I’m curious if I can provide a fix without breaking it - just upgrading versions.

**Comment by MSAdministrator** [comment]
As a side note I would love to see how you’re using it in production sometime.

**Comment by jmeachum** [comment]
> just upgrading versions.

For what we are using it for right now, no I don't think there is any functionality that has been broken. It's a matter of refactoring the code to pull the data we need. It's actually a fairly basic use case at this time but has potential to be used in more depth later on. I'd be happy to explain more about how we are using it. I'd prefer to have that communication via email however. Mind sending me your SL email address? I'll try sending it to what I'd think it would be given the naming convention used by other contacts there.

**Comment by jmeachum** [comment]
> Is there functionality that has changed ? I’m curious if I can provide a fix without breaking it - just upgrading versions.

So the refactoring was minor on the code side.....the tests were a little more involved. I did write a test to help identify the issue identified however I found some odd behavior between tests, which looks to be related to the use of class variables. When a test instantiates an Attck() class the class variables are None as expected. And when the enterprise property is accessed the data is loaded into the class vars. When a subsequent test is called afterwards those vars carry over to the new one. This probably doesn't cause any issues outside of testing, but aside from resetting them on each test I suppose is the way around that. Any reason for use of class vars vs instance? Below is a test to reproduce the behavior. If this is better to be a different issue I can raise it there. I have a test for the update function as well.
`
@pytest.fixture
def attck():
    yield Attck()

def test_class_vars_set(attck):
    assert attck._Attck__ENTERPRISE_ATTCK_JSON is None
    assert attck._Attck__ENTERPRISE_GENERATED_DATA_JSON is None
    assert attck._Attck__ENTERPRISE_NIST_DATA_JSON is None
    techniques = attck.enterprise.techniques
    assert isinstance(techniques, list)
    assert isinstance(attck._Attck__ENTERPRISE_ATTCK_JSON, dict)
    assert isinstance(attck._Attck__ENTERPRISE_GENERATED_DATA_JSON, dict)
    assert isinstance(attck._Attck__ENTERPRISE_NIST_DATA_JSON, dict)


def test_class_vars_persist_tests(attck):
    assert isinstance(attck._Attck__ENTERPRISE_ATTCK_JSON, dict)
    assert isinstance(attck._Attck__ENTERPRISE_GENERATED_DATA_JSON, dict)
    assert isinstance(attck._Attck__ENTERPRISE_NIST_DATA_JSON, dict)
`

**Comment by MSAdministrator** [comment]
@jmeachum thanks for this!  Yes, please create a separate issue and I will take a look at this.  Thanks for point it out and you are correct these probably should be instance variables instead of class variables. Originally I choose class variables so that loading of the data would happen once instead of continually loading from disk but this is less of a concern now that Enterprise, Mobile, etc. are in their own classes.

**Comment by MSAdministrator** [comment]
@jmeachum unrelated (kind of) to this but I’m refactoring pyattck’s handling of external data (e.g. enterprise ATT&CK Json, contextual data Json, etc.) and I’m allowing the user to set these paths to either a URL or a local file path when they instantiate the Attck class. Additionally they can pass in a config file like they can now. 

Does this sound useful? (Also adding proxy support).

**Comment by jmeachum** [comment]
> @jmeachum unrelated (kind of) to this but I’m refactoring pyattck’s handling of external data (e.g. enterprise ATT&CK Json, contextual data Json, etc.) and I’m allowing the user to set these paths to either a URL or a local file path when they instantiate the Attck class. Additionally they can pass in a config file like they can now.
> 
> Does this sound useful? (Also adding proxy support).

@MSAdministrator - Sorry for the late reply. I've used data_path to do just that, specify a different path on instantiation. I actually use it in a test though to confirm the files are pulled on instantiation by checking that path afterwards. The suggestion on providing a url, I think it could be useful.

Regarding proxy support, if the verify property of requests could be set, that would help for situations where there is an intermediary certificate, e.g. SSL inspection is enabled and the cert is signed by internal CAs. Requests will look at an environment variable to provide the path to certs to use in SSL verification but you wouldn't be able to turn off verification if that is something someone needs to do, e.g. troubleshooting. You could implement either by name or pass **kwargs to requests. Setting the refresh frequency of the files would also be useful, as an argument during instantiation as well as in the config file. I can raise that as a request.

**Comment by MSAdministrator** [comment]
@jmeachum   Please checkout the new release which resolves this issue and adds much better handling of configuration going forward.  

```
pip install pyattck==4.0.0
```
