### ISSUE TITLE
Cannot extract DataSource's

### ISSUE THREAD

**Issue by TiiTcHY** [swimlane/pyattck#65]
I am trying to pull the DataSources for the techniques but I keep getting the follow error:

AttributeError: 'AttckTechnique' object has no attribute 'data_source'

**Comment by MSAdministrator** [comment]
@TiiTcHY Can you please tell me which version of `pyattck` you are using that is causing this error?  Also which operating system are you using it on.

Thanks,

**Comment by TiiTcHY** [comment]
I am using it on Windows 10 and the version is pyattck 3.0.1

**Comment by MSAdministrator** [comment]
@TiiTcHY  Please checkout the new release which resolves this issue and adds much better handling of configuration going forward.  

```
pip install pyattck==4.0.0
```
