### ISSUE TITLE
Enterprise data is same as mobile data in latest version 4.0.1

### ISSUE THREAD

**Issue by liavst2** [swimlane/pyattck#70]
Upgraded to the latest 4.0.1.
The following code passes for `malwares`, `actors`, `mitigation`, `tools`, and `tactics`. Seems like the data is completely identical except for `techniques`.

![Screenshot from 2021-06-29 11-50-01](https://user-images.githubusercontent.com/18532875/123768077-b10abc00-d8d0-11eb-90f3-1d20da74faf1.png)

Did not occur in v3.0.1.

**Comment by liavst2** [comment]
Fixed in https://github.com/swimlane/pyattck/pull/71.

**Comment by MSAdministrator** [comment]
This is resolved.
