### ISSUE TITLE
Pillow requirement (Python Imaging Library)

### ISSUE THREAD

**Issue by Neo23x0** [swimlane/pyattck#85]
I noticed that builds on my build systems failed due to a missing `libjpeg-dev` that is required by `Pillow` `9.0.0` that is used in your project. 

Could you explain why pyattck requires an imaging library?
I can't find any hints in the source code.

**Comment by MSAdministrator** [comment]
Hey @Neo23x0 it is used to generate ascii art for logos on Actors. Really it was a “why not” feature and I plan on removing it in the next release anyways.

**Comment by Neo23x0** [comment]
Okay, thanks. Yes, please, every import comes with dependencies that sometimes break things.
