### ISSUE TITLE
Get tools directly from a technique

### ISSUE THREAD

**Issue by aacienfuegos** [swimlane/pyattck#92]
I'm trying to get the tools used for a specific technique and I see that the Technique object doesn't have a property with the tools.

Although the opposite is availible (getting the techniques related to a specific tool), I would like to get the tools from the technique itself, just like it's done with Actors, Mitigations, etc. I've tried to add a new propperty to technique.py and it seems to work fine (it's already being done with the tool's property in actors).

If there's a reason this isn't being done already, either because it's not possible or it's not how you are "supposed" to use the matrix, please let me know.

**Comment by MSAdministrator** [comment]
@aacienfuegos I’ll get this incorporated into the next release.

**Comment by aacienfuegos** [comment]
Awesome! Thank you.
