### ISSUE TITLE
Deprecated attribute accessible in all objects

### ISSUE THREAD

**Issue by aacienfuegos** [swimlane/pyattck#97]
I want to see if the AttckObject is deprecated, at the moment this is only possible with techniques. I would like to do the same with the other objects.

Just like it's done with techniques, you would access the "deprecated" attribute. I beleive this can be done with the x_mitre_deprecated attribute in the JSON files.

I think this attribute is relevant for any type of AttckObject, but if not, it can be created only in certain types.

**Comment by MSAdministrator** [comment]
This has been implemented in #102
